name: "Node Setup (checkout + setup-node + npm ci)"
description: "Common Node setup: checkout, setup Node, install dependencies"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  cache:
    description: "Package manager to cache"
    required: false
    default: "npm"
  full_checkout:
    description: "Use fetch-depth: 0 (true/false)"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.full_checkout == 'true' && 0 || 1 }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: bash
      run: npm ci