name: "Node Setup (setup-node + npm ci)"
description: "Common Node setup: setup Node, install dependencies"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "20"
  cache:
    description: "Package manager to cache"
    required: false
    default: "npm"
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: bash
      run: npm ci